// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: example/demo/demo.proto

package demo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_example_demo_demo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_demo_demo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_example_demo_demo_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the greetings.
type HelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	mi := &file_example_demo_demo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_example_demo_demo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_example_demo_demo_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// The request message for countdown
type CountdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         int32                  `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountdownRequest) Reset() {
	*x = CountdownRequest{}
	mi := &file_example_demo_demo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountdownRequest) ProtoMessage() {}

func (x *CountdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_demo_demo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountdownRequest.ProtoReflect.Descriptor instead.
func (*CountdownRequest) Descriptor() ([]byte, []int) {
	return file_example_demo_demo_proto_rawDescGZIP(), []int{2}
}

func (x *CountdownRequest) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

// The response message for countdown
type CountdownReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountdownReply) Reset() {
	*x = CountdownReply{}
	mi := &file_example_demo_demo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountdownReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountdownReply) ProtoMessage() {}

func (x *CountdownReply) ProtoReflect() protoreflect.Message {
	mi := &file_example_demo_demo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountdownReply.ProtoReflect.Descriptor instead.
func (*CountdownReply) Descriptor() ([]byte, []int) {
	return file_example_demo_demo_proto_rawDescGZIP(), []int{3}
}

func (x *CountdownReply) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_example_demo_demo_proto protoreflect.FileDescriptor

const file_example_demo_demo_proto_rawDesc = "" +
	"\n" +
	"\x17example/demo/demo.proto\x12\x04demo\"\"\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"&\n" +
	"\n" +
	"HelloReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"(\n" +
	"\x10CountdownRequest\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x05R\x05start\"&\n" +
	"\x0eCountdownReply\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count2r\n" +
	"\x04Demo\x12-\n" +
	"\x05Hello\x12\x12.demo.HelloRequest\x1a\x10.demo.HelloReply\x12;\n" +
	"\tCountdown\x12\x16.demo.CountdownRequest\x1a\x14.demo.CountdownReply0\x01B:Z8github.com/tsaarni/grpc-capture-interceptor/example/demob\x06proto3"

var (
	file_example_demo_demo_proto_rawDescOnce sync.Once
	file_example_demo_demo_proto_rawDescData []byte
)

func file_example_demo_demo_proto_rawDescGZIP() []byte {
	file_example_demo_demo_proto_rawDescOnce.Do(func() {
		file_example_demo_demo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_demo_demo_proto_rawDesc), len(file_example_demo_demo_proto_rawDesc)))
	})
	return file_example_demo_demo_proto_rawDescData
}

var file_example_demo_demo_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_example_demo_demo_proto_goTypes = []any{
	(*HelloRequest)(nil),     // 0: demo.HelloRequest
	(*HelloReply)(nil),       // 1: demo.HelloReply
	(*CountdownRequest)(nil), // 2: demo.CountdownRequest
	(*CountdownReply)(nil),   // 3: demo.CountdownReply
}
var file_example_demo_demo_proto_depIdxs = []int32{
	0, // 0: demo.Demo.Hello:input_type -> demo.HelloRequest
	2, // 1: demo.Demo.Countdown:input_type -> demo.CountdownRequest
	1, // 2: demo.Demo.Hello:output_type -> demo.HelloReply
	3, // 3: demo.Demo.Countdown:output_type -> demo.CountdownReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_example_demo_demo_proto_init() }
func file_example_demo_demo_proto_init() {
	if File_example_demo_demo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_demo_demo_proto_rawDesc), len(file_example_demo_demo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_example_demo_demo_proto_goTypes,
		DependencyIndexes: file_example_demo_demo_proto_depIdxs,
		MessageInfos:      file_example_demo_demo_proto_msgTypes,
	}.Build()
	File_example_demo_demo_proto = out.File
	file_example_demo_demo_proto_goTypes = nil
	file_example_demo_demo_proto_depIdxs = nil
}
