name: Build Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Build
        run: |
          go build -o grpc-json-sniffer-viewer cmd/grpc-json-sniffer-viewer/viewer.go
          go build -o server example/server/server.go
          go build -o client example/client/client.go
